/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


CREATE TABLE IF NOT EXISTS `CENTRO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(200) NOT NULL,
  `ACTIVO` tinyint(1) NOT NULL,
  `IDZONA` bigint(20) NOT NULL,
  `CODIGO` varchar(15) NOT NULL,
  `LATENCIASEGURIDAD` int(10) unsigned NOT NULL,
  `LOGO` varchar(300) DEFAULT NULL,
  `GMT` decimal(14,2) NOT NULL,
  `URLMapa` text,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNICA_CODIGO` (`CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE `CENTRO` DISABLE KEYS */;
INSERT INTO `CENTRO` (`ID`, `NOMBRE`, `ACTIVO`, `IDZONA`, `CODIGO`, `LATENCIASEGURIDAD`, `LOGO`, `GMT`, `URLMapa`) VALUES
	(1, 'Centro Sur', 1, 1, 'CENSUR', 0, NULL, 2.00, NULL),
	(2, 'Centro Norte', 1, 1, 'CENNOR', 0, NULL, 1.00, NULL),
	(3, 'Centro Este', 0, 1, 'CENEST', 0, NULL, 1.00, NULL),
	(4, 'Centro Oeste', 1, 2, 'CENOEST', 0, NULL, 1.00, NULL);
/*!40000 ALTER TABLE `CENTRO` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(100) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `APELLIDO1` varchar(100) NOT NULL,
  `APELLIDO2` varchar(100) NOT NULL,
  `TELEFONO1` varchar(100) NOT NULL,
  `TELEFONO2` varchar(100) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `ACTIVO` tinyint(1) NOT NULL,
  `PASSWORD2` varchar(255) DEFAULT NULL,
  `PASSWORD3` varchar(255) DEFAULT NULL,
  `PASSWORD4` varchar(255) DEFAULT NULL,
  `PASSWORD5` varchar(255) DEFAULT NULL,
  `INDEXPASSWORD` int(11) NOT NULL,
  `FECHAMODIFICACIONPASSWORD` datetime NOT NULL,
  `NUMERO_INTENTOS` int(11) NOT NULL,
  `FECHAHORA_OPERACION` datetime DEFAULT NULL,
  `CODIGO_OPERACION` bigint(20) DEFAULT NULL,
  `IDIDIOMA` bigint(20) NOT NULL DEFAULT '1',
  `NUEVO` tinyint(1) NOT NULL,
  `IDCENTRO` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDCENTRO` (`IDCENTRO`),
  CONSTRAINT `FK_USUARIOS_CENTRO` FOREIGN KEY (`IDCENTRO`) REFERENCES `CENTRO` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE `USUARIO` DISABLE KEYS */;
INSERT INTO `USUARIO` (`ID`, `EMAIL`, `NOMBRE`, `APELLIDO1`, `APELLIDO2`, `TELEFONO1`, `TELEFONO2`, `PASSWORD`, `ACTIVO`, `PASSWORD2`, `PASSWORD3`, `PASSWORD4`, `PASSWORD5`, `INDEXPASSWORD`, `FECHAMODIFICACIONPASSWORD`, `NUMERO_INTENTOS`, `FECHAHORA_OPERACION`, `CODIGO_OPERACION`, `IDIDIOMA`, `NUEVO`, `IDCENTRO`) VALUES
	(2, 'sara.manzano@orquestasoluciones.es', 'Sara', 'Manzano', 'Perez', '900675400', '626489874', '1234', 1, NULL, NULL, NULL, NULL, 1, '2018-03-08 10:13:27', 0, '2018-03-08 10:13:32', NULL, 1, 0, 1),
	(3, 'magracia@orquestasoluciones.es', 'MªÁngeles', 'Gracia', 'Campos', '952782091', '687543908', '789456', 1, NULL, NULL, NULL, NULL, 1, '2018-03-08 12:19:17', 0, '2018-03-08 12:19:17', NULL, 1, 0, 1);
/*!40000 ALTER TABLE `USUARIO` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
